### ISSUE TITLE
installed but app <- wpd.launch() returns Error: could not find function "wpd.launch"

### ISSUE THREAD

**Issue by seanread** [ankitrohatgi/digitizeR#1]
system is linux mint 17.3, clean install of R via cran repositories

**Comment by ankitrohatgi** [comment]
Did you load the library before calling wpd.launch?

    library('digitizeR') # before calling wpd.launch()

If this works, then I can add it to the README. I missed adding this point.

**Comment by seanread** [comment]
yup, that did the trick. Thanks!

On Mon, 11 Jan 2016 at 16:28 Ankit Rohatgi <notifications@github.com> wrote:

> Did you load the library before calling wpd.launch?
>
> library('digitizeR') # before calling wpd.launch()
>
> If this works, then I can add it to the README. I missed adding this point.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ankitrohatgi/digitizeR/issues/1#issuecomment-170434978>
> .
>
-- 
Sean Read
Level 1 Yantra Yoga Instructor
